const isDev = false
const isTestNet = false
import {stakeAbi} from './abi.js'
export const providerUrl = isTestNet ? 'https://data-seed-prebsc-1-s1.bnbchain.org:8545' : 'https://rpc.ankr.com/eth'
export const chainId = isTestNet ? '0x61' : '0x1'
export const thlmContractAddress = isTestNet ? '0x803d58Ff1E4A07C9eEfcf9aa5E4a7Fd49e1EbdaE' :'0x0c1b0b010290509b79cAd5F6A669D7865947Be10' 
export const thlmContractAbi = [
    {
        "inputs":[],
        "stateMutability":"nonpayable",
        "type":"constructor"
    },
    {
        "anonymous":false,
        "inputs":
        [
            {
                "indexed":true,
                "internalType":"address",
                "name":"owner",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"spender",
                "type":"address"
            },
            {
                "indexed":false,
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
            }
        ],
        "name":"Approval",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"from",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "indexed":false,
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
            }
        ],
        "name":"Transfer",
        "type":"event"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"owner",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"spender",
                "type":"address"
            }
        ],
        "name":"allowance",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"spender",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"amount",
                "type":"uint256"
            }
        ],
        "name":"approve",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {"inputs":[
        {"internalType":"address","name":"account","type":"address"}
    ],
    "name":"balanceOf",
    "outputs":[
        {"internalType":"uint256","name":"","type":"uint256"}
    ],
    "stateMutability":"view",
    "type":"function"
},{
    "inputs":[
        {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"burn",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
},{
    "inputs":[
        {"internalType":"address","name":"account","type":"address"},
        {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"burnFrom",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
},
{
    "inputs":[],
    "name":"decimals",
    "outputs":[
        {"internalType":"uint8","name":"","type":"uint8"}
    ],
    "stateMutability":"view",
    "type":"function"
},{
    "inputs":[
        {"internalType":"address","name":"spender","type":"address"},
        {"internalType":"uint256","name":"subtractedValue","type":"uint256"}
    ],
    "name":"decreaseAllowance",
    "outputs":[
        {"internalType":"bool","name":"","type":"bool"}
    ],
    "stateMutability":"nonpayable",
    "type":"function"
},
{
    "inputs":[
        {"internalType":"address","name":"spender","type":"address"},
        {"internalType":"uint256","name":"addedValue","type":"uint256"}
    ],
    "name":"increaseAllowance",
    "outputs":[
        {"internalType":"bool","name":"","type":"bool"}
    ],
    "stateMutability":"nonpayable",
    "type":"function"
},{
    "inputs":[],
    "name":"name",
    "outputs":[
        {"internalType":"string","name":"","type":"string"}
    ],
    "stateMutability":"view",
    "type":"function"
},{
    "inputs":[],
    "name":"symbol",
    "outputs":[
        {"internalType":"string","name":"","type":"string"}
    ],
    "stateMutability":"view",
    "type":"function"
},{
    "inputs":[],"name":"totalSupply",
    "outputs":[
        {"internalType":"uint256","name":"","type":"uint256"}
    ],
    "stateMutability":"view",
    "type":"function"
},{
    "inputs":[
        {"internalType":"address","name":"to","type":"address"},
        {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"transfer",
    "outputs":[
        {"internalType":"bool","name":"","type":"bool"}
    ],
    "stateMutability":"nonpayable","type":"function"
},{
    "inputs":[
        {"internalType":"address","name":"from","type":"address"},
        {"internalType":"address","name":"to","type":"address"},
        {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"transferFrom",
    "outputs":[
        {"internalType":"bool","name":"","type":"bool"}
    ],
    "stateMutability":"nonpayable",
    "type":"function"
}]

export const stakeContractAddress = isTestNet ? '0xe0C6F7e1A6B35d6177Aa0B9c9369fA7a0C084b47' : '0x7355a6832b9b55B49B244f477F16b47297BDF194'
export const stakeContractAbi = stakeAbi

export const apiUrl = isDev ? 'http://103.119.106.13:15220/' : 'https://membership.thlm.bond/'
// export const apiUrl = isDev ? 'http://103.119.106.13:15220/' : 'http://103.119.106.13:15120/'
// export const apiUrl = isDev ? 'http://192.168.32.18:3320/' : 'http://103.119.106.13:15220/'

export const productUrl = isDev ? "/Static/airdropStake" : "/Static/html/thlmairdrop"